version: '3.4'

services:
  mysql:
    image: mysql/mysql-server:latest
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "tp-backend"
      MYSQL_ROOT_PASSWORD: "${DB_PW}"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
